# search for requirement files
# default: True
# allowed: True, False
search: False

# Specify requirement files by hand, default is empty
# default: empty
# allowed: list
requirements:
 - docs/requirements.txt
 - tools/requirements_flake8.txt
 - tools/requirements_mypy.txt
 - tools/wpt/requirements.txt
 - tools/wptrunner/requirements.txt
 - tools/wptrunner/requirements_chrome.txt
 - tools/wptrunner/requirements_chrome_android.txt
 - tools/wptrunner/requirements_edge.txt
 - tools/wptrunner/requirements_firefox.txt
 - tools/wptrunner/requirements_ie.txt
 - tools/wptrunner/requirements_opera.txt
 - tools/wptrunner/requirements_safari.txt
 - tools/wptrunner/requirements_sauce.txt
 - tools/wptrunner/requirements_servo.txt
