[tox]
envlist = py39,py310,py311,py312,py313,py314
skipsdist = True
skip_missing_interpreters = False

[testenv]
deps =
  -r{toxinidir}/../requirements_pytest.txt

commands = pytest -c{toxinidir}/../pytest.ini --rootdir={toxinidir} {posargs}

passenv =
  PY_COLORS
