#!/usr/bin/env python3
"""Sync the pins in tools/**/requirements*.txt with tools/constraints.txt.

tools/constraints.txt is generated by ``uv pip compile`` and records the
fully resolved version of every direct and transitive dependency. The
individual ``requirements*.txt`` files each pin a handful of direct
dependencies by hand, and those pins drift from what constraints.txt
resolves to over time. This rewrites just the version part of each
``==`` pin to match constraints.txt, leaving everything else (formatting,
comments, markers, extras, unresolvable lines) untouched.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Dict, List, Mapping, Optional, Sequence, Tuple

from packaging.markers import Marker
from packaging.utils import NormalizedName, canonicalize_name

from ...wpt import virtualenv
from .compile import CONSTRAINTS_PATH, REPO_ROOT, compile_constraints, find_input_files
from .requirements_file import Entry, RequirementLine, RequirementsFile

# canonical package name -> resolved (version, marker, marker_text) triples.
# More than one entry for a name means constraints.txt resolved different
# versions of that package under different markers. marker_text is the
# marker clause exactly as written in constraints.txt, for verbatim reuse.
Constraints = Mapping[NormalizedName, Sequence[Tuple[str, Optional[Marker], Optional[str]]]]


def build_constraints(constraints: RequirementsFile) -> Constraints:
    result: Dict[NormalizedName, List[Tuple[str, Optional[Marker], Optional[str]]]] = {}
    for entry in constraints.entries:
        if not isinstance(entry, RequirementLine):
            continue
        specs = list(entry.requirement.specifier)
        if len(specs) != 1 or specs[0].operator != "==":
            raise ValueError(f"{entry.requirement.name}: constraints.txt pin isn't a single '=='")
        name = canonicalize_name(entry.requirement.name)
        result.setdefault(name, []).append((specs[0].version, entry.requirement.marker, entry.marker_text))
    return result


def count_names(entries: Sequence[Entry]) -> Mapping[NormalizedName, int]:
    counts: Dict[NormalizedName, int] = {}
    for entry in entries:
        if isinstance(entry, RequirementLine):
            name = canonicalize_name(entry.requirement.name)
            counts[name] = counts.get(name, 0) + 1
    return counts


def resolve_pin(
    requirement_name: str,
    requirement_marker: Optional[Marker],
    current_version: str,
    constraints: Constraints,
    line_count: int,
) -> Tuple[Optional[str], Optional[str], Optional[str]]:
    """Return (new_version, new_marker_text, error); error is None on success."""
    entries = constraints.get(canonicalize_name(requirement_name))
    if not entries:
        return None, None, "not in constraints.txt"

    if len(entries) == 1:
        version, marker, marker_text = entries[0]
        if marker is None and line_count > 1:
            # constraints.txt only resolved one (unmarked) version of this
            # package, but this file pins it multiple times under
            # different markers - we can't tell which line that version
            # belongs to.
            return None, None, (
                "constraints.txt has a single unmarked pin but this file pins it "
                f"{line_count} times under different markers"
            )
        return version, marker_text, None

    marker_matches = [(version, marker_text) for version, marker, marker_text in entries if marker == requirement_marker]
    if len(marker_matches) == 1:
        return marker_matches[0][0], marker_matches[0][1], None

    # No marker matches. Fall back to pairing by the version this line is
    # currently pinned to, so we can adopt constraints.txt's marker for it.
    version_matches = [
        (version, marker_text) for version, _marker, marker_text in entries if version == current_version
    ]
    if len(version_matches) == 1:
        return version_matches[0][0], version_matches[0][1], None

    return None, None, "ambiguous: no single matching marker or version in constraints.txt"


def sync_requirement(
    entry: RequirementLine, constraints: Constraints, name_counts: Mapping[NormalizedName, int]
) -> Tuple[RequirementLine, Optional[str]]:
    name = entry.requirement.name
    specs = list(entry.requirement.specifier)
    if len(specs) != 1 or specs[0].operator != "==":
        return entry, f"{name}: not a single '==' pin, left untouched"

    line_count = name_counts[canonicalize_name(name)]
    version, marker_text, error = resolve_pin(
        name, entry.requirement.marker, specs[0].version, constraints, line_count
    )
    if error is not None:
        return entry, f"{name}: {error}, left untouched"
    assert version is not None

    if version == specs[0].version and marker_text == entry.marker_text:
        return entry, None

    new_entry = entry.with_pin(version, marker_text)
    if marker_text != entry.marker_text:
        return new_entry, f"{name}: {specs[0].version} -> {version}, marker updated to match constraints.txt"
    return new_entry, f"{name}: {specs[0].version} -> {version}"


def sync_file(path: Path, constraints: Constraints, check: bool) -> bool:
    parsed = RequirementsFile.parse(path.read_text())
    name_counts = count_names(parsed.entries)
    rel_path = path.relative_to(REPO_ROOT)

    changed = False
    new_entries: list[Entry] = []
    for entry in parsed.entries:
        if isinstance(entry, RequirementLine):
            new_entry, message = sync_requirement(entry, constraints, name_counts)
            if message:
                print(f"{rel_path}: {message}")
            changed = changed or new_entry is not entry
            new_entries.append(new_entry)
        else:
            new_entries.append(entry)

    if changed and not check:
        path.write_text(str(RequirementsFile(new_entries, parsed.trailing_newline)))
    return changed


def relax_pins(path: Path) -> None:
    parsed = RequirementsFile.parse(path.read_text())
    relaxed_entries = [
        entry.relaxed() if isinstance(entry, RequirementLine) else entry
        for entry in parsed.entries
    ]
    path.write_text(str(RequirementsFile(relaxed_entries, parsed.trailing_newline)))


def upgrade_constraints() -> None:
    """Relax every tracked '==' pin to '>=' and re-run `uv pip compile`.

    This gives the resolver room to pick up newer versions than whatever's
    currently pinned. The relax is purely transient: every tracked file is
    restored to its original text once compilation finishes (or fails), so
    only tools/constraints.txt itself ends up changed here - the actual
    pin bumps happen afterwards, via the normal sync in run() below.
    """
    input_files = find_input_files()
    originals = {path: path.read_text() for path in input_files}
    for path in input_files:
        relax_pins(path)
    try:
        compile_constraints()
    finally:
        for path, text in originals.items():
            path.write_text(text)


def get_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--constraints",
        type=Path,
        default=CONSTRAINTS_PATH,
        help="path to the constraints file to sync against (default: %(default)s); "
             "ignored if --upgrade is passed",
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--check",
        action="store_true",
        help="only report what would change; exit with a nonzero status if anything is out of sync",
    )
    mode.add_argument(
        "--upgrade",
        action="store_true",
        help="relax every tracked '==' pin to '>=' and regenerate tools/constraints.txt first, "
             "so the resolver can pick up newer versions, then sync pins as normal",
    )
    return parser


def run(venv: Optional[virtualenv.Virtualenv], constraints: Path, check: bool, upgrade: bool) -> Optional[int]:
    if upgrade:
        upgrade_constraints()
        constraints = CONSTRAINTS_PATH

    constraints_file = RequirementsFile.parse(constraints.read_text())
    parsed_constraints = build_constraints(constraints_file)

    any_changed = False
    for path in find_input_files():
        if sync_file(path, parsed_constraints, check):
            any_changed = True

    return 1 if check and any_changed else None


def main() -> None:
    sys.exit(run(None, **vars(get_parser().parse_args())) or 0)


if __name__ == "__main__":
    main()
